apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.labels" . | nindent 8 }}
      {{- if .Values.metrics.enabled }}
      annotations:
        prometheus.io/scrape: "{{ .Values.metrics.scrape }}"
        prometheus.io/port: "{{ .Values.metrics.port }}"
        prometheus.io/path: "{{ .Values.metrics.path }}"
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.containerPort }}
          ports:
            - containerPort: {{ . }}
              name: http
            {{- if .Values.metrics.enabled }}
            - containerPort: {{ .Values.metrics.port }}
              name: metrics
            {{- end }}
          {{- end }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if and .Values.externalSecrets.enabled .Values.externalSecrets.mountAsEnv }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secrets
          {{- end }}
          {{- if .Values.configMap.enabled }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name | default (printf "%s-config" .Release.Name) }}
          {{- end }}
          {{- if or (and .Values.externalSecrets.enabled .Values.externalSecrets.mountAsFile) (.Values.configMap.mountAsFile) }}
          volumeMounts:
            {{- if and .Values.externalSecrets.enabled .Values.externalSecrets.mountAsFile }}
            {{- range .Values.externalSecrets.parameters }}
            - name: secrets-volume
              mountPath: {{ .mountPath }}
              subPath: {{ .key }}
            {{- end }}
            {{- end }}
            {{- if .Values.configMap.mountAsFile }}
            - name: config-volume
              mountPath: {{ .Values.configMap.mountPath }}
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if and .Values.externalSecrets.enabled .Values.externalSecrets.mountAsFile }}
        - name: secrets-volume
          secret:
            secretName: {{ .Release.Name }}-secrets
        {{- end }}
        {{- if .Values.configMap.mountAsFile }}
        - name: config-volume
          configMap:
            name: {{ .Values.configMap.name | default (printf "%s-config" .Release.Name) }}
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}