apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lavalink
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kevinfinalboss/Personal-Lab.git 
    targetRevision: HEAD
    path: charts/app-templates/deployment
    helm:
      releaseName: lavalink
      values: |
        replicaCount: 1
        
        image:
          repository: "registry.kevindev.com.br/lavalink"
          tag: "master"
          pullPolicy: Always
        
        imagePullSecrets:
          - name: regcred
        
        containerPort: 2333
        
        service:
          type: ClusterIP
          port: 2333
        
        configMap:
          enabled: false
        
        persistence:
          enabled: false
        
        volumes:
          - name: config-volume
            configMap:
              name: lavalink-config
        
        volumeMounts:
          - name: config-volume
            mountPath: /opt/lavalink/application.yml
            subPath: application.yml
        
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        
        metrics:
          enabled: false
        
        env:
          - name: JAVA_OPTS
            value: "-Xmx512m -Xms256m -Dcom.sun.management.jmxremote=false"
          - name: YOUTUBE_REFRESH_TOKEN
            valueFrom:
              secretKeyRef:
                name: lavalink-oauth-secret
                key: youtube-refresh-token
                  
  destination:
    server: https://kubernetes.default.svc 
    namespace: lavalink 
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true